Repository YunoHost/moulinette, pull requests merged in 2018-12, with the labels that each got.

#171 Protect against CSRF
  moulinette/interfaces/api.py
  setup.py
  tests/test_api.py
Labels: important, opinion needed, small decision

#174 Remove Access-Control-Allow-Origin
  moulinette/interfaces/api.py
Labels: opinion needed, small decision

#184 [enh] Display date as system timezone
  debian/control
  moulinette/interfaces/cli.py
  moulinette/utils/serialize.py
Labels: opinion needed, ready to merge, small decision

#181 Add possiblity to get attribute name of conflict in LDAP
  moulinette/authenticators/ldap.py
Labels: opinion needed, ready to merge, small decision

#180 [enh] Simplify moulinette errors
  locales/en.json
  moulinette/__init__.py
  moulinette/actionsmap.py
  moulinette/authenticators/__init__.py
  moulinette/authenticators/ldap.py
  moulinette/core.py
  moulinette/interfaces/__init__.py
  moulinette/interfaces/api.py
  moulinette/interfaces/cli.py
  moulinette/utils/filesystem.py
  moulinette/utils/network.py
Labels: opinion needed, small decision

#187 Autopep8
  moulinette/actionsmap.py
  moulinette/authenticators/__init__.py
  moulinette/authenticators/ldap.py
  moulinette/core.py
  moulinette/interfaces/__init__.py
  moulinette/interfaces/api.py
  moulinette/interfaces/cli.py
  moulinette/utils/filesystem.py
  moulinette/utils/log.py
  moulinette/utils/process.py
  moulinette/utils/serialize.py
  moulinette/utils/stream.py
Labels: opinion needed, small decision

#182 Make sure `gpg.encrypt` actually does something
  moulinette/authenticators/__init__.py
Labels: opinion needed, small decision
